#!/usr/bin/env bash

TEXT="MRCPP, a numerical library based on multiresolution analysis and"
AUTHORS="Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors."

python .githooks/license_maintainer.py "$TEXT" "$AUTHORS"
