coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto 
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto 
