coverage:
  notify:
    slack:
      default:
        url: secret:bInnBtjHWqcMiw+KB/NyVFU2yk6gHLdMLmgIdh1wT/VK0OetNc+WP2gYxhQwEy6yoJyRBSmpMfKwn4RuVSEe6orVQNMpt3NS9g53B2btW7a1Iv3SCl+GhPVkVHQiwarhWgFQnbR4QYQyBI5wTOOC1QanuUVn0yQ05FMz/VnMRU8=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
        attachments: "sunburst, diff"
  ignore:
    - "tests/*"
    - "external/*"
    - "/usr/*"
