coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
  ignore:
    - "tests/*"
    - "external/*"
    - "/usr/*"
