if(NOT DEFINED ENV{CXXFLAGS})
    if(CMAKE_CXX_COMPILER_ID MATCHES Intel)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ftz -fp-speculation=safe -fp-model source -Wno-unknown-pragmas")
        set(CMAKE_CXX_FLAGS_RELEASE "-O2 -xHost -DNDEBUG")
        set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -xHost -debug -DNDEBUG")
        set(CMAKE_CXX_FLAGS_DEBUG "-O0 -debug -DDEBUG")
    endif()
endif()
