# Adapted from: https://github.com/psi4/psi4meta/blob/master/conda-recipes/conda_build_config.yaml
# <<<  Compiler Stuff  >>>

cxx_compiler:
    - clangxx                          # [osx]
    - gxx                              # [linux]
target_platform:
    - osx-64                           # [osx]
    - linux-64                         # [linux]
CONDA_BUILD_SYSROOT:
    - /Users/github/SDKs/MacOSX10.9.sdk  # [osx]
cxx_compiler_version:
    - 7.3.0                            # [linux]

# <<<  Packages Stuff  >>>

blas_impl:
    - mkl
mkl:
    - 2019  # 15 Aug 2019

# <<<  MRCPP Stuff  >>>

OPTS:
    - '-msse4.1'                                                                    # [osx]
    - '-msse2 -axCORE-AVX512,CORE-AVX2,AVX -Wl,--as-needed -static-intel -wd10237'  # [linux]
