name: Build and test MRCPP

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # setup-miniconda not compatible with macos-latest presently.
        # https://github.com/conda-incubator/setup-miniconda/issues/344
        # macos-12 temporarily removed since it keeps failing
        os: [ubuntu-latest]  #, macos-12]

    steps:
    - uses: actions/checkout@v4

    - name: Cache conda
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 0  # Increase this value to reset cache if .github/mrcpp-gha.yml has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/mrcpp-gha.yml') }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: mrcpp-gha
          environment-file: .github/mrcpp-gha.yml
          channel-priority: true
          python-version: 3.11
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!

    - name: Configure
      shell: bash -l {0}
      run: |
        python ./setup --type=$BUILD_TYPE --omp --enable-examples --generator=Ninja --prefix=$GITHUB_WORKSPACE/Software/MRCPP build
    - name: Build
      shell: bash -l {0}
      run: |
        cmake --build build --config $BUILD_TYPE --target install -- -v -d stats

    - name: Test
      shell: bash -l {0}
      run: |
        cd build
        ctest -C $BUILD_TYPE --output-on-failure --verbose
