/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_G0_5() noexcept -> Eigen::Matrix<double, 6, 6> {
  return (Eigen::Matrix<double, 6, 6>() << 0.300609066011366, -0.449145913112748, 0.151630593432455, 0.331783421477544, -0.151676670972776, -0.227649401528936, 0.203315095747961, -0.40651876118469, 0.419603555787759, -0.0853632986205272, -0.326257643852113, -0.0600614826059288, 0.105189857736655, -0.255607362856292, 0.41215305640558, -0.444113050775135, 0.0612549751925792, 0.22965464098052, -0.0329676316650577, 0.0950942486640881, -0.214153234052242, 0.420628180691541, -0.513002862106181, -0.0625188656116374, -0.00140269300305089, 0.00813255383127497, -0.0372910664825716, 0.151048134128623, -0.478828173807616, 0.496436613804258, 0.00261818668829961, -0.00687411882471992, 0.0125370548818338, -0.0097510337134616, -0.0999533490942962, 0.699787795828201).finished();
}
} // namespace mrcpp
} // namespace detail
