/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_G0_4() noexcept -> Eigen::Matrix<double, 5, 5> {
  return (Eigen::Matrix<double, 5, 5>() << -0.326941513673996, 0.481433551241372, -0.112429454849704, -0.379141094200058, -0.0703038458881032, -0.204042572537827, 0.426495114394576, -0.454219979166135, 0.0268746624091728, 0.263496696443072, 0.0884881931595718, -0.23575288549719, 0.435991019423961, -0.488385091162843, -0.0893434405125519, 0.0174077389292808, -0.0604975311160823, 0.182750518995111, -0.485877803070747, 0.475985322929595, -0.00239221479666362, 0.00432697414643599, 0.00701615575878308, -0.123612716783385, 0.696165371453437).finished();
}
} // namespace mrcpp
} // namespace detail
