/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_G0_7() noexcept -> Eigen::Matrix<double, 8, 8> {
  return (Eigen::Matrix<double, 8, 8>() << 0.262817672425819, -0.398141356199219, 0.174980709231904, 0.237755106362816, -0.321454067174212, -0.14468720816636, 0.172437797933183, 0.176812591954769, 0.197540839202943, -0.373951609443285, 0.361635250811728, -0.0972928789193724, -0.268718904363576, 0.242998557076412, 0.220250023722706, 0.0335205977014286, 0.126864210009541, -0.279333295928421, 0.385134313031723, -0.362562948339986, 0.109474963090719, 0.257479913507829, -0.125451711676088, -0.179106800694017, -0.0625056488572121, 0.153900627261688, -0.265934522839602, 0.382914073802686, -0.410478606556149, 0.152376027737477, 0.246446374786129, 0.0511500393034783, 0.0185473796848801, -0.0510691203731173, 0.108344062813722, -0.214349611367012, 0.381023684050491, -0.485983604881768, 0.14396109237703, 0.193079878991296, 7.51385727680334e-05, 0.0017734669751545, -0.0112147662897267, 0.0449861897166082, -0.148674470030747, 0.390632731246409, -0.568113989072827, -0.0198944107914425, -0.00266423627903507, 0.00666474459920358, -0.0118224965334692, 0.0167629146880807, -0.00740808492329211, -0.0900799081191275, 0.460676654634627, -0.528332723382738, 0.00105377534689364, -0.00279849485475513, 0.00574265802077893, -0.0116009772615274, 0.0235737587221642, -0.0372353437550399, -0.0574398414820356, 0.703265219440839).finished();
}
} // namespace mrcpp
} // namespace detail
