/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_G0_6() noexcept -> Eigen::Matrix<double, 7, 7> {
  return (Eigen::Matrix<double, 7, 7>() << -0.279809581491283, 0.421614736873095, -0.168494999655965, -0.279371482098651, 0.273342705688121, 0.247599014939063, 0.0385631285860873, -0.200956723611622, 0.389479712424434, -0.388746211955581, 0.0997637515455838, 0.29875220923974, -0.134177592823565, -0.198969888353107, -0.117740620768601, 0.269995461581748, -0.397735684072584, 0.400838275746119, -0.109487890788458, -0.281970302108893, -0.0536632999152045, -0.0483991018500276, 0.126628976288711, -0.242513658783281, 0.395849464206892, -0.460780931699521, 0.102601670430494, 0.20800669821388, 0.008837403576162, -0.027775727275403, 0.072358493934097, -0.182424184488002, 0.406595687724685, -0.54196169994478, -0.0399191314846146, 0.00252137824709832, -0.00545519592206072, 0.00524532025134873, 0.0137775465116932, -0.119891534973428, 0.470464078099564, -0.51384445153802, -0.00178151301675868, 0.00479072288023185, -0.00990147814506646, 0.0188833078419747, -0.0244204412576447, -0.0779826021791025, 0.702026788952745).finished();
}
} // namespace mrcpp
} // namespace detail
