/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_H0_4() noexcept -> Eigen::Matrix<double, 5, 5> {
  return (Eigen::Matrix<double, 5, 5>() << 0.888229977602501, 0.448034101463787, -0.0352763171031282, -0.0715405018035812, -0.0104272804455427, -0.20024209800317, 0.529787821550162, 0.742167468709392, 0.312898854714934, 0.0363194641485971, 0.103377895580658, -0.188611864171565, 0.0677643998637108, 0.495132878168314, 0.451652515178333, -0.0556628925986484, 0.0934895608227404, -0.0274930325107305, -0.125163651503367, -0.0304984567870023, 0.0224103771099092, -0.0366214542801235, 0.010189684546835, 0.0424994034133702, 0.00940084103592884).finished();
}
} // namespace mrcpp
} // namespace detail
