/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_H0_6() noexcept -> Eigen::Matrix<double, 7, 7> {
  return (Eigen::Matrix<double, 7, 7>() << 0.894183193744222, 0.437626435766692, -0.0556556202660076, -0.0505842781943495, 0.0340897469727113, 0.0245576187300229, 0.00339502860222559, -0.20800560607032, 0.565130110216574, 0.755985858177865, 0.200363993121606, -0.106534855906548, -0.0700483254773676, -0.00932864180569166, 0.116100024865148, -0.213991648312389, 0.133837264065655, 0.700162852368307, 0.593016966320301, 0.211222194482379, 0.0239217228279268, -0.0741306502340038, 0.125013132872513, -0.0618900226703192, -0.144262410268863, 0.237563084530601, 0.494665787018462, 0.39128491589158, 0.0478318958745611, -0.0779322060760286, 0.0358596563688819, 0.0727759344692262, -0.0917613258830031, -0.109191852811185, -0.0210989746971899, -0.0282445441902703, 0.0452982699980329, -0.0202066441160178, -0.0389794097574169, 0.0455896638677215, 0.0492559241852236, 0.00870964812728439, 0.0118281830665005, -0.0188390401719934, 0.00829379222183986, 0.0156770930471989, -0.017836475604155, -0.0186713816023353, -0.00321773714275413).finished();
}
} // namespace mrcpp
} // namespace detail
