/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_I_H0_3() noexcept -> Eigen::Matrix<double, 4, 4> {
  return (Eigen::Matrix<double, 4, 4>() << 0.881804597105976, 0.458300536030939, -0.00714661780635641, -0.067606192722111, -0.191774644439248, 0.491057988740705, 0.704173296233134, 0.365971624573627, 0.0891422650220798, -0.160453814928387, 0.0104803125297076, 0.241842240384463, -0.0341715503410443, 0.057214213751572, -0.00318664643523247, -0.0575176836516122).finished();
}
} // namespace mrcpp
} // namespace detail
