/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_G0_3() noexcept -> Eigen::Matrix<double, 4, 4> {
  return (Eigen::Matrix<double, 4, 4>() << 6.54942861656366e-76, -0.153392997769474, -0.594088525786005, 0.351467511677404, -0.154303349962092, -0.267261241912424, -0.172516389835589, 0.612372435695794, -1.98162199167824e-75, -0.0878668779193509, -0.340306954864886, -0.613571991077896, 0.215645487294486, 0.373508940416998, 0.443622131141014, 0.342326598440729).finished();
}
} // namespace mrcpp
} // namespace detail
