/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_G0_7() noexcept -> Eigen::Matrix<double, 8, 8> {
  return (Eigen::Matrix<double, 8, 8>() << -5.16061388171798e-74, 0.0394514921576236, 0.152794972109509, 0.301315748485445, 0.204995966554227, -0.528806992464036, 0.246374489558189, -0.0441081091391231, 0.0843312289034136, 0.146065973125433, 0.16163173753211, 0.0637484169813985, -0.216851731465921, -0.399564349117425, 0.456090854901223, -0.163306722554063, 7.5318383290282e-72, -0.0258430814883384, -0.100089824219016, -0.212700425618062, -0.25588832464672, 0.0103051686103246, 0.496282756040329, -0.363580920890125, 0.0742292692888546, 0.128568865817008, 0.150304516117234, 0.103644762948322, -0.0669121025632302, -0.309991123262385, -0.23335025635848, 0.538147107915713, 1.70202875421197e-71, 0.0213434791213834, 0.0826629391872435, 0.182959231101958, 0.269218188725434, 0.196827002538047, -0.180532124571329, -0.561628047792797, -0.0871939722326493, -0.151024390020698, -0.184102234147577, -0.166389240058105, -0.052029314926153, 0.183637591370366, 0.440134468134723, 0.421736491643413, 8.90762748696094e-72, -0.0192854509208144, -0.0746922302404146, -0.172371744816637, -0.299250122582079, -0.405043262634304, -0.400361235182952, -0.224582556324644, 0.130994289272089, 0.226888764520633, 0.289907908446133, 0.328805065784445, 0.333689839232842, 0.290099600883833, 0.194575209516251, 0.0763964570434043).finished();
}
} // namespace mrcpp
} // namespace detail
