/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_G0_4() noexcept -> Eigen::Matrix<double, 5, 5> {
  return (Eigen::Matrix<double, 5, 5>() << -0.146647115021353, -0.254000254000381, -0.163956458945988, 0.581987695247378, -0.21997067253203, -8.21350255410548e-75, 0.0702439358686271, 0.272053593791254, 0.429197537639476, -0.486664263392288, -0.122012412152228, -0.211331697001693, -0.208908333645302, 0.0553396284716417, 0.627492405354315, 1.06119063668378e-74, 0.0536496922049345, 0.207784364438865, 0.439024599178919, 0.511081959901582, 0.184174088668056, 0.318998879010768, 0.395016566365812, 0.387834176035668, 0.240553911729705).finished();
}
} // namespace mrcpp
} // namespace detail
