/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_H0_4() noexcept -> Eigen::Matrix<double, 5, 5> {
  return (Eigen::Matrix<double, 5, 5>() << 0.707106781186548, 0, 2.44267733951092e-77, 0, -8.3967033545688e-78, -0.612372435695794, 0.353553390593274, -1.71750750434362e-77, 2.36634367265121e-77, 1.90834167149291e-78, 1.52667333719433e-78, -0.684653196881458, 0.176776695296637, -4.12201801042468e-77, -8.3967033545688e-78, 0.233853586673371, 0.405046293650491, -0.522912516583797, 0.0883883476483184, 8.3967033545688e-78, 1.67934067091376e-77, 0.153093108923949, 0.592927061281571, -0.350780380010057, 0.0441941738241592).finished();
}
} // namespace mrcpp
} // namespace detail
