/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_H0_6() noexcept -> Eigen::Matrix<double, 7, 7> {
  return (Eigen::Matrix<double, 7, 7>() << 0.707106781186548, -1.52667333719433e-78, 6.41202801621617e-77, -7.63336668597164e-79, 7.02269735109391e-77, 0, 2.5571778398005e-77, -0.612372435695794, 0.353553390593274, -5.48648230554211e-77, 6.56469534993561e-77, -6.12577676549224e-77, 1.10683816946589e-76, -2.46056804268117e-77, 9.16004002316596e-78, -0.684653196881458, 0.176776695296637, -1.26713886987129e-76, 3.35868134182752e-77, -2.09154247195623e-76, 2.51901100637064e-77, 0.233853586673371, 0.405046293650491, -0.522912516583797, 0.0883883476483184, -8.53982897993077e-77, 1.44556881615588e-76, -6.32138178682026e-77, 6.33569434935646e-77, 0.153093108923949, 0.592927061281571, -0.350780380010057, 0.0441941738241592, -6.25936068249674e-77, 9.19820685659582e-77, -0.146575492494482, -0.253876200144874, -0.163876382526586, 0.581703452155821, -0.219863238741723, 0.0220970869120796, -9.59895860760933e-77, 1.98467533835263e-77, -0.0689981317681863, -0.26722861525761, -0.421585548851001, 0.478033079399324, -0.132121363478811, 0.0110485434560398).finished();
}
} // namespace mrcpp
} // namespace detail
