/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_H0_5() noexcept -> Eigen::Matrix<double, 6, 6> {
  return (Eigen::Matrix<double, 6, 6>() << 0.707106781186548, 1.52667333719433e-78, 7.78603401969107e-77, 0, 8.8547053557271e-77, -3.81668334298582e-79, -0.612372435695794, 0.353553390593274, -6.47881997471843e-77, 8.76882998050992e-77, -7.8194299989422e-77, 8.88571590788886e-77, 2.13734267207206e-77, -0.684653196881458, 0.176776695296637, -1.70987413765765e-76, 2.97701300752894e-77, -1.6946074042857e-76, 0.233853586673371, 0.405046293650491, -0.522912516583797, 0.0883883476483184, -6.05898480698999e-77, 1.29576399494369e-76, 7.02269735109391e-77, 0.153093108923949, 0.592927061281571, -0.350780380010057, 0.0441941738241592, -6.71736268365504e-77, -0.146575492494482, -0.253876200144874, -0.163876382526586, 0.581703452155821, -0.219863238741723, 0.0220970869120796).finished();
}
} // namespace mrcpp
} // namespace detail
