/*
 * MRCPP, a numerical library based on multiresolution analysis and
 * the multiwavelet basis which provide low-scaling algorithms as well as
 * rigorous error control in numerical computations.
 * Copyright (C) 2019 Stig Rune Jensen, Jonas Juselius, Luca Frediani and contributors.
 *
 * This file is part of MRCPP.
 *
 * MRCPP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MRCPP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MRCPP.  If not, see <https://www.gnu.org/licenses/>.
 *
 * For information on the complete list of contributors to MRCPP, see:
 * <https://mrcpp.readthedocs.io/>
 */

// THIS FILE HAS BEEN AUTOGENERATED, DO NOT TOUCH

#include "FilterData.h"

#include <Eigen/Core>


namespace mrcpp {
namespace detail {
auto get_L_H0_7() noexcept -> Eigen::Matrix<double, 8, 8> {
  return (Eigen::Matrix<double, 8, 8>() << 0.707106781186548, 1.52667333719433e-78, 3.05334667438865e-77, 0, 6.41202801621617e-77, 0, 1.00760440254826e-76, 1.90834167149291e-79, -0.612372435695794, 0.353553390593274, -2.64305321501768e-77, 4.8042501579834e-77, -5.51749285770387e-77, 7.8194299989422e-77, -9.02645610616146e-77, -1.42326507287031e-76, 1.03050450260617e-77, -0.684653196881458, 0.176776695296637, -8.93103902258682e-77, 3.2823476749678e-77, -1.56484017062419e-76, 5.80135868133844e-77, 2.73274527357785e-76, 0.233853586673371, 0.405046293650491, -0.522912516583797, 0.0883883476483184, -7.55226216493319e-77, 1.1831718363256e-76, -1.27286389488577e-76, -2.07269759795024e-76, 4.99985517931142e-77, 0.153093108923949, 0.592927061281571, -0.350780380010057, 0.0441941738241592, -4.42735267786355e-77, 1.84727473800514e-76, 1.00378771920527e-76, -0.146575492494482, -0.253876200144874, -0.163876382526586, 0.581703452155821, -0.219863238741723, 0.0220970869120796, -1.06867133603603e-76, -1.56269328624376e-76, -3.7403496761261e-77, -0.0689981317681863, -0.26722861525761, -0.421585548851001, 0.478033079399324, -0.132121363478811, 0.0110485434560398, 2.5037442729987e-76, 0.106977062012728, 0.185289706650491, 0.181798066847189, -0.0566069404148025, -0.534885310063639, 0.3548027758708, -0.0771422564770762, 0.0055242717280199).finished();
}
} // namespace mrcpp
} // namespace detail
